.github/workflows/coverage.yml
👋 
I just found this mishap on the job upgrade, apologies!
=> ci: Re-add missing buildtype for MSVC coverage checks

impl/meson.build, impl/socket.cxx, substrate/advanced/fd, substrate/console, substrate/conversions, substrate/crypto/sha256, substrate/crypto/sha512, substrate/indexed_iterator, substrate/internal/defs, substrate/iterator, test/advanced/fd.cxx, test/conversions.cxx, test/fd.cxx
Hey @dragonmux,
As promised, here are some fixes for last night's Substrate woes. On the MSVC side of things, I fixed all warnings except:
```
C:\Users\Amalia\Desktop\Rachel\substrate\substrate/console(87): warning C4251: 'substrate::console_t::consoleMutex': class 'std::mutex' needs to have dll-interface to be used by clients of struct 'substrate::console_t'
```
Additionally I fixed your C++ standard check, as, in old AppleClang versions, Meson can downgrade standard under your back and this would go undetected. I also took care of the CI fails regarding `command_line` due to old libstdc++ having an improper definition of `std::variant` internals.
=> Assorted MSVC and CLANG64 fixes

impl/meson.build
👋 
This PR is to fix the wrong variant check you'd told me about last night.
The previous attempt instead banned all compilers due to a typo. After fixing it and having it pass in affected compiler, bisecting [1] revealed I'd run into a different but associated Clang bug [2] [3].
[1]: https://gcc.gnu.org/git/?p=gcc.git;a=history;f=libstdc%2B%2B-v3/include/std/variant;h=35781495e3117ed22ab6fa1745fd0ea2cfc66308;hb=HEAD
[2]: https://bugs.llvm.org/show_bug.cgi?id=31852
[3]: https://bugs.llvm.org/show_bug.cgi?id=33222
=> command_line: Fix working <variant> check

substrate/pointer_utils, test/pointer_utils.cxx
Hi!
This MR proposes adding a neat pattern for automagically dealing with naughty (non-void returning) and nice (void-returning) C-style deleter functions.
Conceptually, they're the same as constructing `std::shared_ptr<T, Deleter>`, only that they allow:
- passing the deleter at compile time (excellent for creating many such complex pointers with a single `using`)
- using said pointers with misbehaving libraries (eg. Fontconfig, which [crashes when faced with a null pointer](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/339)).
=> Naughty & Nice pointers

.github/workflows/coverage.yml, .github/workflows/workflow.yml, README.md, substrate/internal/defs, substrate/utility, test/advanced/fd.cxx, test/fd.cxx
👋 
This MR ensures C++20 is properly supported (apologies for the mishap with constexpr std::string!) and documents it.
For future reference, I've also added CI jobs and fixed the LLVM deployment. Turns out, apt.llvm.org no longer includes multiple versions in the tip toolchain, only the latest. Moreover, `clang++-xy` is only a package that exists in Ubuntu (trying to install it when targeting Clang 13+ ends up with an error).
=> Officially add C++20 support

substrate/fd, substrate/internal/defs
`std::filesystem` APIs are only available starting with macOS 10.15, iOS and tvOS 13.0, and watchOS 6.0. `__cplusplus` or `__cpp_lib_filesystem` values are not enough for checking this.
=> fd: Fix misallowed usage of std::filesystem::path for Apple

.github/workflows/workflow.yml
👋 
Just that, pure Powershell instead of Git Bash for the MSVC build. Also fixes the MSVC version logging.
=> ci: Use powershell consistently for the MSVC build

substrate/bits, substrate/rwlock, test/bits.cxx
This is just an initial draft of `rwlock` for #18, as it uses `std::shared_mutex` it's exclusive to C++17 or newer.
=> rwlock (and bswap8 because oops)

substrate/span
See https://developercommunity.visualstudio.com/t/std::enable_if_t-:-Failed-to-specializ/1650779
=> span: Work around MSVC 2019 rejecting constexpr SFINAE with integral constant conditionals

impl/meson.build, test/meson.build
It carries two bugs:
- an incomplete implementation of filesystem in macOS
- is unable to deduce nullptr == any pointer type value
Also fixes the detection with GCC 8.5 which packs the implementation separately.
=> command_line: Block GCC8 from using the module

substrate/bits
/app/example.cpp:9:26: runtime error: shift exponent 64 is too large for 64-bit type 'unsigned long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /app/example.cpp:9:26 in
See: https://godbolt.org/z/zM1EEz4v8
(I have no idea why it popped up now, but I was able to verify it with `-fsanitize=undefined` pretty easily.)
=> bits: Fix UB in shift_nibble

.clang-format
Hi @dragonmux,
Here's the PR bringing your .clang-format file back. It obviously doesn't cover all your style quirks, but it will now be happily accepted by clangd 😄
=> ci: Fix dragonmux's clang-format file and allow a minimal fallback style

substrate/bits
Hi @dragonmux,
This PR implements workarounds for missed optimizations in MSVC, which [we reported previously](https://developercommunity.visualstudio.com/t/Missed-optimization:-bswap-uint64_t-and-/1035241).
I've not added version checks for the 8-bit and 64-bit cases because I don't know yet when those fixes will be released, 17.7.0 preview 1 is still affected.
=> bits: Add MSVC-specific workarounds for missed optimizations in swap(n)

substrate/span, substrate/utility, substrate/zip_container, test/meson.build, test/zip_container.cxx
Hi @dragonmux,
This PR implements a `zipContainer_t` meta-class that ties a tuple of containers, in order to iterate over them in tandem.
I know this needs changes and formatting, please let me know and I'll take care of it. Filing this first lets me log the comments for my own reference.
=> Add a container zipper class

meson.build
Hi @dragonmux,
Just a small PR adding support for Control Flow Guard in supported compilers.
See:
- https://learn.microsoft.com/en-us/windows/win32/secbp/control-flow-guard
- https://reviews.llvm.org/D65761
- https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#id98
=> windows: Enforce usage of CFG in consumers if supported

impl/affinity.cxx, impl/console.cxx, impl/thread.cxx, substrate/mmap, substrate/pty, substrate/socket, test/affinity.cxx, test/socket.cxx
Hi @dragonmux,
This MR is in preparation for the port to Catch2 v3 which does use much more templating than usual. It streamlines the application of `NOMINMAX` and `WIN32_LEAN_AND_MEAN` across the codebase.
=> windows: Correctly remove the min/max macros

substrate/latch, substrate/thread_pool, substrate/threaded_queue, test/thread_pool.cxx
Hi @dragonmux,
This implements the recommendation of WG21's Ben Craig and GCC's Andrew Pinski and applies locks to the scope in which the condition variable is fired.
I've also preserved, for future debugging, the deinlining of the lambdas-- if ever we need to *cringe* use `std::bind` again.
See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=110016
See https://en.cppreference.com/w/cpp/thread/condition_variable
=> gcc: Fix std::condition_variable::wait inlining not preserving lambda semantics

impl/meson.build, impl/utility.cxx, meson.build, substrate/thread_pool, substrate/utility, test/affinity.cxx, test/utility.cxx
Hi @dragonmux,
This PR fixes some assorted tidbits I found earlier this week.
- Implemented demangling for MSVC through Windows's dbghelp library
- Fixed some loss of precision warnings in affinity_t (mainly caused by discrepancies in how Windows returns processor groups)
- Re-enabled the inlining in threadPool_t, except in the consumer functions for the sake of safety
- Fixed LTO building failure because compile_args isn't exposed anymore in Meson since 1.1.0
=> Fix Windows shenanigans

substrate/span, substrate/utility
Hi @dragonmux,
As in #44, it seems that you implemented `std::data` for pre-17, but without porting it  into `utility`. This PR does just that, allowing me to implement STL container compatibility for all hash functions.
=> utility: Port std::data too

substrate/hash
Hi @dragonmux,
We continue tonight with adding STL compatibility, through `std::data` and `std::size`, to the checksum functions in `hash`.
The next two PRs will implement tests and CRC32 :O
=> Implement STL container compatibility for checksum functions

impl/hash.cxx, impl/meson.build, substrate/hash, test/hash.cxx
Hi @dragonmux,
This PR implements compile-time (where possible) CRC32. I based it on an old Godbolt of yours, and adjusted the necessary bits to make it compatible all the way back to C++11.
Depends on #59 passing and being merged, so marking as draft and submitting for your review (ignore all but the last commit).
=> Implement CRC32

impl/utility.cxx, test/utility.cxx
Hi @dragonmux,
Here's a PR to fix an issue that AppleClang detected in decode_typename. The fallback I implemented for MinGW (first try Itanium if available, then Win32 also if available) did not return a value if the former failed and the latter wasn't available-- which is the case in macOS.
=> utility: Fix decode_typename not returning a value in non-Linux + non-Windows 

.github/workflows/codeql.yml, .github/workflows/workflow.yml
Hi @dragonmux,
There were some bits about the current CI output that were bothering me:
- we duplicated ABI checks a Lot in MSYS2
- CodeQL has no concurrency barrier in case of force pushes
- Meson complains that there's no lcov executable installed when generating the coverage report
- Codecov complains in turn because the C++11 coverage builds don't upload anything (thanks catch2! It needs C++14 minimum)
This PR attempts to fix all of them at once. I've not checked if they work due to the origin check in them, so 🤞
=> ci: Optimize job matrix and fix some Meson warnings

.github/workflows/workflow.yml, gcovr.cfg
Hi @dragonmux,
This PR is to fix #63 which didn't give any heads up that it had actually *fixed* Codecov's coverage calculation in MSYS. In fact, it worked so well that it started considering the whole of catch2 into its numbers.
Meson supports distilling the gcov/gcda/gcno files into a Codecov-compatible coverage.xml file with the `coverage-xml` target. Using that allows us to skip the dance ourselves. However, we must run the target manually-- unsure of what Meson 1.1.0 is doing here, but it doesn't find the target if run through `meson compile`, as the docs say.
=> ci: Use Meson to distill the coverage file

.github/workflows/workflow.yml, meson.build
Hi @dragonmux,
I don't know how this was working previously, but both sets' coverage was broken-- MSVC no longer found OpenCppCoverage because we never wrote the path entry to the correct file (`$env:GITHUB_PATH` since it's PowerShell), and Linux in turn had always returned 0% coverage because of a too old gcovr doing *something* when assembling the report.
While just telling gcovr to use the `-g` flag was enough to fix it in my VM, I prefer to use an actually known working version from pip instead.
=> Fix MSVC and Linux coverage

.github/workflows/workflow.yml, meson.build
Hi @dragonmux,
This PR fixes the following nitpicks with regards to the MSVC jobs:
- they still submitted coverage for the test folder, which we already exclude in the rest of the jobs.
- for the cases where they time out (codegen or deadlock issues?) we'll now submit the test executables and PDB as well, for local testing.
=> ci: Assorted improvements in MSVC

.github/workflows/workflow.yml, meson.build, substrate/hash, substrate/internal/defs
Hi @dragonmux,
This PR is to propose some slight changes to the substrate build defaults, for better codegen out of the box. I also added some fixes that slipped CI since the libraries are usually built as shared. 
=> Assorted codegen fixes

impl/command_line/arguments.cxx, impl/command_line/options.cxx, substrate/command_line/arguments, substrate/command_line/options
In this PR we extend the substrate/command_line/options subsystem to allow the help strings contained within to then be used to generate automatic help listings for programs.
=> Feature:command line options autotomatic help generation

substrate/fd, substrate/internal/fd_compat
This avoids warning C4996 in MSVC.
=> fd: Use non-deprecated close and dup in Windows

substrate/iterator
Hey @dragonmux,
This fixes a lint in clang-tidy:
> Return type 'const iterator_t' is 'const'-qualified at the top level, which may reduce code readability without improving const correctness (fix available) clang-tidy([readability-const-return-type](https://clang.llvm.org/extra/clang-tidy/checks/readability/const-return-type.html))
It's also picked up by MSVC if warning C5266 is enabled.
=> iterator: Remove ineffective const in base() return type

substrate/console
In this PR we aim to fix how `printable_t` is defined and how the `asN_t` types failed to properly define constructors, destructors and assignment operators, thus failing the Rule of 5 requirements on them.
The goal here is to address several MSVC warnings and clang-tidy lints which indicate broken code, with the intent of getting the [blackmagic-debug/bmpflash](https://github.com/blackmagic-debug/bmpflash) build closer to warning-free ahead of cutting releases of this library and that program.
=> Fix: missing constructors and operators in substrate/console

impl/meson.build, substrate/internal/defs
As part of getting CI for bmpflash up and working, we encountered a series of issues surrounding <filesystem> and getting the checks for it being enabled right. This PR seeks to improve this situation by, among other things, including the <version> header to ensure the proper feature macros are available in <substrate/include/defs> and improve the logic for defining the guard macro.
The result should be a much more robust path to getting `SUBSTRATE_ALLOW_STD_FILESYSTEM_PATH` defined in appropriate circumstances.
=> Fix: std::filesystem include issues

substrate/console
This PR fixes a few more type conversions warnings that were popping up in the console header as part of asInt_t::format().
=> Fix: <substrate/console> type conversion warnings

impl/command_line/meson.build, impl/meson.build, meson.build
This PR adds a variable to the build system to denote when the command line parser has been enabled. This is to allow dependent builds to detect this condition and depend on the command line parser.
Additionally, this PR sorts a long-standing issue with the host vs target (native, non-native) builds where state from one would leak into the other in potentially bad ways and cause a malodorous mess if cross-compiling to Windows from Linux (for example).
=> Feature: command line parser enabled var

impl/console.cxx, impl/meson.build, impl/socket.cxx, meson.build, substrate/console, test/console.cxx, test/socket.cxx
This PR aims to improve how we handle strings in console_t/consoleStream_t on Windows and in general Unicode handling on output.
This fixes an issue where std::string's containing UTF-8 would not get converted on Windows, resulting in garbled output.
We also implement support for std::wstring/wchar_t and std::u16String/char16_t strings though the former is only for Windows. This should allow any UTF-16 or wide Windows character strings to be correctly displayed in a program's output just the same as any other strings.
Some of the architectural changes should also provide a nice speed boost for STL string containers by not throwing away the length information only to have to re-calculate it.
=> Feature: Improved Windows console text handling

impl/socket.cxx, substrate/socket
Hey @dragonmux,
Related to dragonmux/rSON#8, this should help you minimise the footprint of its `rpcStream_t` implementation.
=> socket: Expose parameter conversion functions as inline for consumers

impl/socket.cxx, meson.build, substrate/internal/defs, substrate/utility
👋 
This is a PR to add a little feature, marking code at a certain point to be unreachable (and if so, trigger UBSan or abort).
=> Add support for detecting unreachable code

impl/command_line/options.cxx, substrate/command_line/options
👋 
This is a PR to add a placeholder in the options' display text so that the user knows what to enter as values.
=> options: Add contextual value to the helper text

impl/command_line/arguments.cxx, impl/command_line/options.cxx, substrate/command_line/arguments, substrate/command_line/options
In this PR we seek to improve the state of the command line arguments parser by implementing two new features that solve usability problems and bring us closer to parity with Rust's Clap and Python's argparse.
The first of these new features is option exclusivity, whereby you can define multiple options at a parsing level to be exclusive of one another and bypass requirements checks for normal options - this is done with the new options_t helper `.exclusive()` and allows, eg, `--version` and `--help` to be defined and made exclusive of each other + uncaring of other arguments requirements validity.
The second of these features is option globalness, whereby an option can be defined to be "global" (visible to its level and all parsing levels below that) such as a `--help` option that should …
=> Feature: Improved command-line arguments parsing

.github/workflows/codeql.yml
See https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
Fixes #84
=> ci: Update CodeQL actions

substrate/fd, substrate/file_utils, substrate/internal/fd_compat, substrate/mmap, test/file_utils.cxx, test/meson.build
Hey @dragonmux,
This is a PR to add a small line reader to Substrate.
As you'll find in the attached test suite, I wasn't able to make it work with UTF-16 and wchar_t strings. Hope you can assist me in that regard.
Let me know what you think :cat:
=> substrate: Add basic file utility to read all the lines from a file
